tariffer/linea.yml
Lagt til tariffer for Linea
NB: Trinn 1 og 2 har samme pris iflg. nettstedene til Linea både https://cdn.sanity.io/files/roorjgzz/linea-prod/503e6e0465f495e533b592353bbe6889ec300669.pdf og https://www.linea.no/no/kunde/nettleie/nettleiepriser - og er altså ikke en manuell input feil fra min side
=> Linea tariffer

tariffer/kenett.yml
Samlet KE nett. 
Morsom tariff med -2 som grunnpris på energiledd
=> KE Nett tariffer

tariffer/rknett.yml
NB: Det opplyses om energiledd natt og energiledd dag, men det er samme pris. På spørsmål og svar står det at det er billigere på natten. Har sendt mail for å avklare
=> RK Nett tariff

tariffer/rakkestadenerginett.yml
NB: Kan være en idé å vente med å merge, eller så kommer jeg med en ny commit når jeg får svar. Årsaken er at Tariff med ID 2024-07-privat mangler historiske terskler over trinn 5, grunnet at historiske priser mangler dette. Har sendt e-post for å få tilsendt dette.
=> Rakkestad Energi Nett Tariffer

tariffer/kenett.yml
=> KE Nett tariffer for 2025

tariffer/midtnett.yml
Prisene er uendret, kun avgiften er endret. Fått bekreftet på mail
=> Korrigering for Midtnett 2025

tariffer/kenett.yml
=> Spesifiser gjeldene dager for unntak på energiledd i KE Nett

tariffer/bindal-kraftlag.yml, tariffer/elmea.yml
=> La til Bindal og Elmea. Begge har 2025 priser

tariffer/meloy.yml
Let's go! Jævlig bra jobba med 100% dekning!
Sorry for lite deltagelse i det siste - utrolig mye på tallerkenen grunnet sykdom og ferie på de andre utviklerne.
=> Meløy 2025 priser

docs/innsamler/index.html
Brukte en super enkel funksjon som setter tilbake til nr igjen bare for å være sikker på at jeg ikke kødder noe med tallene som går til yaml-fila. 
Gjorde kjapp QA, så greit ut, men ikke super trygg i javascript så se gjerne over !
=> Avrunding i inputfeltene, løser #43

tariffer/meloy.yml
=> fix: meløy tariff

tariffer/havnett.yml
=> fix: havnett

tariffer/elvia.yml
=> samle elvia 2025-04-01

tariffer/etna.yml
=> samle etna for 2025-03

tariffer/elvenett.yml
https://www.elvenett.no/media/guapqy0g/nye-priser-privat-01042025_nye-trinn.pdf
=> samle elvenett 2025-04-01

tariffer/kenett.yml
https://ke-nett.no/Nettleiepriser/
=> samle KE 2025-05-01

tariffer/midtnett.yml
=> fiks midnett sine priser. closes #119

tariffer/tendranett.yml
=> samle tendranett for 2025-06-01

tariffer/lnett.yml
=> Nye priser for Lnett

tariffer/sygnir.yml
Fiffig move fra sygnir. De har økt prisen tilsvarende reduksjonen i elavgift som regjeringen innfører fra 1. juli (4,4 øre)
=> samle sygnir for 2025-07-01

tariffer/vestall.yml
[Direktelenke til innsamler ](https://kraftsystemet.no/fri-nettleie/innsamler/?data=ewogICJnbG4iOiBbCiAgICAiNzA4MDAwNTA1MTg5NyIKICBdLAogICJraWxkZXIiOiBbCiAgICAiaHR0cHM6Ly92ZXN0YWxsLm5vL25ldHRsZWllLyIsCiAgICAiaHR0cHM6Ly92ZXN0YWxsLm5vL25ldHRsZWllcHJpc2VyLWZyYS0wMS0wNy0yMDI1LyIKICBdLAogICJuZXR0ZWllciI6ICJWZXN0YWxsIEFTIiwKICAic2lzdF9vcHBkYXRlcnQiOiAiMjAyNS0wNy0wMiIsCiAgInRhcmlmZmVyIjogWwogICAgewogICAgICAiZW5lcmdpbGVkZCI6IHsKICAgICAgICAiZ3J1bm5wcmlzIjogNC4zLAogICAgICAgICJ1bm50YWsiOiBbCiAgICAgICAgICB7CiAgICAgICAgICAgICJuYXZuIjogIkRhZyIsCiAgICAgICAgICAgICJwcmlzIjogOC42LAogICAgICAgICAgICAidGltZXIiOiAiNi0yMSIKICAgICAgICAgIH0KICAgICAgICBdCiAgICAgIH0sCiAgICAgICJmYXN0bGVkZCI6IHsKICAgICAgICAibWV0b2RlIjogIlRSRV9EXHUwMGQ4R05NQVhfTU5EIiwKICAgICAgICAidGVyc2tlbF9pbmtsdWRlcnQiOiB0cnVlLAogICAgICAgICJ0ZXJza2xl …
=> samle vestall 2025-07-01. closes #145

tariffer/barentsnett.yml
Betydelig nedgang i tariffer 👌
Merk at Barents Nett er unntatt MVA og forbruksavgift
https://www.barents-nett.no/aktuelt/barents-nett-as-setter-ned-nettleien-fra-1-juli-2025
[Lenke til utfylt innsamler](https://kraftsystemet.no/fri-nettleie/innsamler/?data=eyJuZXR0ZWllciI6IkJhcmVudHMgTmV0dCBBUyIsImdsbiI6WyI3MDgwMDA1MDUxOTM0Il0sImtpbGRlciI6WyJodHRwczovL3d3dy5iYXJlbnRzLW5ldHQubm8va3VuZGVzZXJ2aWNlL25ldHQtb2ctbmV0dGxlaWUvIiwiaHR0cHM6Ly93d3cuYmFyZW50cy1uZXR0Lm5vL2dldGZpbGUucGhwLzEzMTQxMTYtMTc1MTAwNzUzMi9Eb2t1bWVudGVyL05ldHQvTmV0dGxlaWUvTmV0dGxlaWVicm9zanlyZSUyMDAxLjA3LjIwMjUucGRmIl0sInNpc3Rfb3BwZGF0ZXJ0IjoiMjAyNS0wNy0wMiIsInRhcmlmZmVyIjpbeyJrdW5kZWdydXBwZSI6InByaXZhdCIsImZhc3RsZWRkIjp7Im1ldG9kZSI6IlRSRV9E2EdOTUFYX01ORCIsInRlcnNrZWxfaW5rbHVkZXJ0Ijp0cnVlLCJ0ZXJza2xlciI6W3sidGVyc2tlbCI6MCwicHJpcyI …
=> sandnose: update barents nett

tariffer/vevig.yml
Ingen nedsettelse hos vevig
[Lenke til utfylt innsamler](https://kraftsystemet.no/fri-nettleie/innsamler/?data=eyJnbG4iOlsiNzA4MDAwMzgwNzk0NiJdLCJraWxkZXIiOlsiaHR0cHM6Ly92ZXZpZy5uby9uZXR0bGVpZS1vZy12aWxrYXIvbmV0dGxlaWUtcHJpdmF0LyJdLCJuZXR0ZWllciI6IlZldmlnIEFTIiwic2lzdF9vcHBkYXRlcnQiOiIyMDI1LTA3LTAyIiwidGFyaWZmZXIiOlt7ImVuZXJnaWxlZGQiOnsiZ3J1bm5wcmlzIjoxMy40LCJ1bm50YWsiOlt7Im5hdm4iOiJI+HlsYXN0IiwicHJpcyI6MjEuNCwidGltZXIiOiI2LTIxIn1dfSwiZmFzdGxlZGQiOnsibWV0b2RlIjoiVFJFX0TYR05NQVhfTU5EIiwidGVyc2tlbF9pbmtsdWRlcnQiOmZhbHNlLCJ0ZXJza2xlciI6W3sicHJpcyI6MjAxNiwidGVyc2tlbCI6MH0seyJwcmlzIjoyNjE2LCJ0ZXJza2VsIjoyfSx7InByaXMiOjM2MzYsInRlcnNrZWwiOjV9LHsicHJpcyI6NDY2OCwidGVyc2tlbCI6MTB9LHsicHJpcyI6NTY4OCwidGVyc2tlbCI6MTV9LHsicHJpcyI6NjY5NiwidGVyc2tlbCI6MjB9LHsicHJpcyI6NzcxNiwidGVyc2tlbCI6MjV9LHsicHJpcyI6O …
=> sandnose: update vevig

tariffer/vestmar.yml
=> samle vestmar 2025-07-01

tariffer/glitre.yml
=> samle glitre for 2025-09-01

tariffer/foere.yml
Prisen på siste ledd var oppgitt i månedspris ikke årspris
=> Pris fiks Føre

tariffer/etna.yml
=> Etna Oktober 2025

tariffer/snett.yml
Kapasitetsledd prisene for terskel 2 og fram var ink mva
=> S-Nett Kapasitetsledd priser var ink mva
